# Generated by Django 2.2.19 on 2021-03-13 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shiire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scode', models.CharField(max_length=30)),
                ('sname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bango',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcode', models.CharField(max_length=200)),
                ('se', models.CharField(max_length=30, unique=True)),
                ('shiire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bango.Shiire')),
            ],
        ),
    ]
