# Generated by Django 2.2.19 on 2021-03-14 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sebango', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bango.Bango')),
            ],
        ),
    ]
