# Generated by Django 2.2.19 on 2021-03-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bango', '0003_label_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
